import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {useApp} from './store';
import {bridgeRequest} from './api';
import {Modal,Notice,Field} from './ui';
const GpuTerminal=lazy(()=>import('./GpuTerminal').then(m=>({default:m.GpuTerminal}))); 
type Kind='shell'|'command'|'experiment';
type Task={id:string;kind:Kind;state:string;description:string;user:string;pool:string;startTime:string;endTime?:string;active:boolean;configYaml?:string;configSummary?:{image?:string;slots?:number};};
type Agent={id:string;pools:string[];slotsTotal:number;slotsFree:number;slots:{id:string;state:string;mine?:boolean;taskId?:string;user?:string}[]};
type Overview={user:string;cluster:{name:string};pools:{name:string;slotsAvailable:number;slotsTotal:number;queued:number}[];agents:Agent[];tasks:Record<Kind,Task[]>;warnings:string[]};
type Log={id:number|string;ts:string;msg:string;level:string};
type Metrics={ts:number;gpus:{util:number;memUsed:number;memTotal:number;temp:number;power:number}[];ram?:{used:number;total:number};};
type Tmux={available:boolean;reason?:string;selectedPane?:string;content?:string;sessions:{name:string;windows:{index:number;panes:{id:string;index:number;command:string}[]}[]}[]};
const date=(s?:string)=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—';
const kinds:Kind[]=['shell','command','experiment'];
const labels={shell:'Shell',command:'命令',experiment:'实验'};
export function GpuNative({revision,onApply}:{revision:number;onApply:(p:string)=>void}){
 const {data,secrets}=useApp();const [overview,setOverview]=useState<Overview|null>(null),[error,setError]=useState(''),[pool,setPool]=useState(''),[kind,setKind]=useState<Kind>('shell'),[mine,setMine]=useState(false),[interval,setIntervalSeconds]=useState(30),[selected,setSelected]=useState<{kind:Kind;id:string}|null>(null),[updated,setUpdated]=useState('');
 const busy=useRef(false);
 const api=(path:string)=>bridgeRequest(data.settings,secrets,'/gpu/dashboard',{path});
 async function refresh(){if(busy.current)return;busy.current=true;try{const r=await api('/api/overview');setOverview(r);setUpdated(new Date().toLocaleTimeString('zh-CN'));setError('');}catch(e){setError((e as Error).message);}finally{busy.current=false;}}
 useEffect(()=>{void refresh();if(!interval)return;const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},interval*1000);return()=>clearInterval(t);},[revision,interval,secrets.bridgeKey]);
 async function openSlot(id:string){const t=kinds.flatMap(k=>overview?.tasks[k]||[]).find(t=>t.id===id);if(t){setSelected({id,kind:t.kind});return;}for(const k of kinds){try{await api(`/api/task/${k}/${id}`);setSelected({id,kind:k});return;}catch{}}setError('集群未返回此槽位任务的详情，请检查当前账号在集群中的权限。');}
 const tasks=(overview?.tasks[kind]||[]).filter(t=>(!mine||t.user===overview?.user)&&(!pool||t.pool===pool)).sort((a,b)=>Number(b.active)-Number(a.active)||Date.parse(b.startTime)-Date.parse(a.startTime));
 return <section className="gpu-native"><div className="gpu-native-toolbar"><span>{overview?.cluster.name||'实验室集群'} · {overview?.user||'未连接'} {updated&&`· ${updated}`}</span><select aria-label="刷新间隔" value={interval} onChange={e=>setIntervalSeconds(Number(e.target.value))}>{[0,5,10,30].map(n=><option key={n} value={n}>{n?`${n} 秒刷新`:'暂停'}</option>)}</select><button className="secondary" onClick={()=>void refresh()}>刷新资源</button></div>
 {error&&<Notice tone="warning">{error}</Notice>}{overview?.warnings?.length?<Notice tone="warning">{overview.warnings.join('；')}</Notice>:null}
 <div className="gpu-pool-tabs"><button className={!pool?'primary':'secondary'} onClick={()=>setPool('')}>全部资源池</button>{overview?.pools.map(p=><button key={p.name} className={pool===p.name?'primary':'secondary'} onClick={()=>setPool(p.name)}>{p.name} · {p.slotsAvailable}/{p.slotsTotal} 空闲</button>)}</div>
 <div className="section-heading"><h2>节点与 GPU</h2><div className="button-group">{['s3-4090','d2-a800'].map(p=><button className="secondary" key={p} onClick={()=>onApply(p)}>申请 {p}</button>)}</div></div>
 <div className="gpu-node-grid">{overview?.agents.filter(a=>!pool||a.pools.includes(pool)).map(a=><article className="gpu-node" key={a.id}><h3>{a.id}</h3><p className="muted">{a.pools.join(' · ')} · 空闲 {a.slotsFree}/{a.slotsTotal}</p><div className="gpu-slot-grid">{a.slots.map(s=><button key={s.id} className={`gpu-slot ${s.state==='free'?'available':s.state==='disabled'?'disabled':'allocated'} ${s.mine?'gpu-mine':''}`} disabled={s.state==='disabled'} title={s.taskId||'点击申请'} onClick={()=>{if(s.taskId)void openSlot(s.taskId);else{const p=a.pools.find(p=>['s3-4090','d2-a800'].includes(p));if(p)onApply(p);else setError('此资源池未配置申请模板');}}}><strong>GPU {s.id}</strong><span>{s.state==='free'?'空闲':s.state==='disabled'?'禁用':s.mine?'我的任务':s.user||'已占用'}</span></button>)}</div></article>)}</div>
 <div className="section-heading"><h2>集群任务</h2><label><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/> 仅我的任务</label></div><div className="gpu-pool-tabs">{kinds.map(k=><button key={k} className={kind===k?'primary':'secondary'} onClick={()=>setKind(k)}>{labels[k]} · {overview?.tasks[k]?.length||0}</button>)}</div>
 <div className="surface gpu-task-table"><table><thead><tr><th>状态</th><th>任务 / ID</th><th>用户</th><th>资源池</th><th>开始日期</th><th/></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><span className={'status-tag '+(t.state==='RUNNING'?'success':'')}>{t.state}</span></td><td>{t.description}<small>{t.id}</small></td><td>{t.user}</td><td>{t.pool||'—'}</td><td>{date(t.startTime)}</td><td><button className="text-button" onClick={()=>setSelected({id:t.id,kind})}>详情</button></td></tr>)}</tbody></table>{!tasks.length&&<p className="muted">暂无可显示的任务。</p>}</div>
 {selected&&<GpuTaskDrawer key={selected.kind+selected.id} {...selected} onClose={()=>setSelected(null)} onChanged={()=>void refresh()}/>}
 </section>;
}
function GpuTaskDrawer({id,kind,onClose,onChanged}:{id:string;kind:Kind;onClose:()=>void;onChanged:()=>void}){
 const {data,secrets}=useApp();const [detail,setDetail]=useState<Task|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[terminal,setTerminal]=useState(false),[expanded,setExpanded]=useState(false),[confirm,setConfirm]=useState(''),[killing,setKilling]=useState(false);
 const api=(suffix='',method='GET',body={})=>bridgeRequest(data.settings,secrets,'/gpu/dashboard',{path:`/api/task/${kind}/${id}${suffix}`,method,body});
 async function refresh(){try{setDetail(await api());setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},15000);return()=>clearInterval(t);},[id,kind]);
 return <Modal drawer expanded={expanded&&tab==='terminal'} title={`${labels[kind]} · 任务详情`} onClose={onClose}><div className="gpu-detail"><h3>{detail?.description||id}</h3><p className="gpu-break"><code>{id}</code></p><p>{detail?.state} · {detail?.user} · {detail?.pool}</p><div className="gpu-pool-tabs">{[['overview','概览'],['logs','日志'],...(kind==='shell'?[['terminal','终端'],['tmux','tmux']]:[])].map(([k,label])=><button className={tab===k?'primary':'secondary'} key={k} onClick={()=>setTab(k)}>{label}</button>)}</div>{error&&<Notice tone="warning">{error}</Notice>}
 {tab==='overview'&&<><dl><dt>开始日期</dt><dd>{date(detail?.startTime)}</dd><dt>结束日期</dt><dd>{date(detail?.endTime)}</dd><dt>显卡数量</dt><dd>{detail?.configSummary?.slots??'—'}</dd><dt>镜像</dt><dd>{detail?.configSummary?.image||'—'}</dd></dl>{kind==='shell'&&detail?.state==='RUNNING'&&<GpuLiveMetrics id={id}/>}<details><summary>完整配置 YAML</summary><pre className="gpu-config-preview">{detail?.configYaml||'集群未提供配置'}</pre></details><details style={{marginTop:24}}><summary>终止任务并释放资源</summary><Notice tone="warning">终止会结束此任务的全部进程并释放其显卡。请输入完整任务 ID。</Notice><input aria-label="确认终止的任务 ID" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="primary" disabled={confirm!==id||killing||!detail?.active} onClick={async()=>{setKilling(true);try{await api('/kill','POST',{confirm});setConfirm('');await refresh();onChanged();}catch(e){setError((e as Error).message+'；请先刷新状态核对，勿直接重试。');}finally{setKilling(false);}}}>{killing?'正在终止…':'终止此任务'}</button></details></>}
 {tab==='logs'&&<GpuLogs id={id} kind={kind}/>}
 {tab==='terminal'&&<button className="secondary gpu-terminal-expand" onClick={()=>setExpanded(v=>!v)}>{expanded?'还原到侧栏':'放大终端'}</button>}<div className="gpu-terminal-host" style={{display:tab==='terminal'?'block':'none'}}>{terminal&&<Suspense fallback={<p>正在加载终端…</p>}><GpuTerminal taskId={id}/></Suspense>}</div>{tab==='terminal'&&<><p className="gpu-terminal-origin">连接的是当前任务容器，不是本机或宿主机。</p><button className="primary" disabled={!terminal&&detail?.state!=='RUNNING'} onClick={()=>setTerminal(v=>!v)}>{terminal?'断开终端':'连接交互终端'}</button></>}
 {tab==='tmux'&&<GpuTmux id={id} onTerminal={()=>{setTab('terminal');setTerminal(true);}}/>}
 </div></Modal>;
}
function GpuLiveMetrics({id}:{id:string}){
 const {data,secrets}=useApp();const [samples,setSamples]=useState<Metrics[]>([]),[error,setError]=useState('');
 useEffect(()=>{let alive=true,busy=false;async function read(){if(busy||document.visibilityState!=='visible')return;busy=true;try{const r=await bridgeRequest(data.settings,secrets,'/gpu/dashboard',{path:`/api/task/shell/${id}/metrics`});if(alive){setSamples(s=>[...s,r].slice(-60));setError('');}}catch(e){if(alive)setError((e as Error).message);}finally{busy=false;}}void read();const t=setInterval(read,5000);return()=>{alive=false;clearInterval(t);};},[id]);
 const last=samples.at(-1),series=[...(last?.gpus||[]).flatMap((_,i)=>[{label:`GPU ${i+1} 利用率`,unit:'%',values:samples.map(s=>s.gpus[i]?.util),max:100},{label:`GPU ${i+1} 显存`,unit:'GiB',values:samples.map(s=>s.gpus[i]?s.gpus[i].memUsed/1024:undefined),max:(last?.gpus[i].memTotal||1024)/1024}]),{label:'容器可见内存',unit:'GiB',values:samples.map(s=>s.ram?s.ram.used/1048576:undefined),max:(last?.ram?.total||1048576)/1048576}];
 return <section><h3>资源消耗</h3><p className="muted">每 5 秒检查 · {last?`采样于 ${date(new Date(last.ts*1000).toISOString())}`:'等待采样'}</p>{error&&<Notice tone="warning">{error}</Notice>}{series.map(s=><div className="metric-chart" key={s.label}><strong>{s.label} · {s.values.at(-1)?.toFixed(1)??'—'} {s.unit}</strong><svg viewBox="0 0 400 100" role="img" aria-label={s.label}><path d={s.values.map((v,i)=>v===undefined?'':`${i===0||s.values[i-1]===undefined||samples[i].ts-samples[i-1].ts>20?'M':'L'}${i*390/Math.max(1,s.values.length-1)},${95-Math.min(1,v/Math.max(1,s.max))*90}`).join(' ')} fill="none" stroke="var(--accent)" strokeWidth="2"/></svg></div>)}</section>;
}
function GpuLogs({id,kind}:{id:string;kind:Kind}){
 const {data,secrets}=useApp();const [logs,setLogs]=useState<Log[]>([]),[error,setError]=useState(''),[filter,setFilter]=useState(''),[follow,setFollow]=useState(true),[noise,setNoise]=useState(true);const pre=useRef<HTMLPreElement>(null);
 useEffect(()=>{let alive=true,busy=false;async function read(){if(busy||document.visibilityState!=='visible')return;busy=true;try{const r=await bridgeRequest(data.settings,secrets,'/gpu/dashboard',{path:`/api/task/${kind}/${id}/logs?limit=500`});if(alive){setLogs(r.entries);setError('');}}catch(e){if(alive)setError((e as Error).message);}finally{busy=false;}}void read();const t=follow?setInterval(read,5000):null;return()=>{alive=false;if(t)clearInterval(t);};},[id,kind,follow]);
 useEffect(()=>{if(follow&&pre.current)pre.current.scrollTop=pre.current.scrollHeight;},[logs,follow]);
 return <section><Field label="过滤日志"><input value={filter} onChange={e=>setFilter(e.target.value)}/></Field><div className="button-group"><label><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/> 跟随最新</label><label><input type="checkbox" checked={noise} onChange={e=>setNoise(e.target.checked)}/> 隐藏 SSH 噪声</label></div>{error&&<Notice tone="warning">{error}</Notice>}<pre ref={pre} className="gpu-output">{logs.filter(l=>l.msg.includes(filter)&&(!noise||!/sshd|Accepted publickey|Disconnected from/i.test(l.msg))).map(l=>`${l.ts||''} ${l.msg}`).join('\n')||'暂无日志'}</pre></section>;
}
function GpuTmux({id,onTerminal}:{id:string;onTerminal:()=>void}){
 const {data,secrets}=useApp();const [snapshot,setSnapshot]=useState<Tmux|null>(null),[pane,setPane]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true,busy=false;async function read(){if(busy||document.visibilityState!=='visible')return;busy=true;setLoading(true);try{const r=await bridgeRequest(data.settings,secrets,'/gpu/dashboard',{path:`/api/task/shell/${id}/tmux?lines=200${pane?'&pane='+encodeURIComponent(pane):''}`});if(alive){setSnapshot(r);setError('');if(!pane){const first=r.sessions?.[0]?.windows?.[0]?.panes?.[0]?.id;if(first)setPane(first);}}}catch(e){if(alive)setError((e as Error).message);}finally{busy=false;if(alive)setLoading(false);}}void read();const t=setInterval(read,7000);return()=>{alive=false;clearInterval(t);};},[id,pane,refresh]);
 return <section><div className="button-group"><button className="secondary" onClick={()=>setRefresh(r=>r+1)}>刷新会话</button><button className="primary" onClick={onTerminal}>进入交互终端</button></div><p>{loading?'正在读取 tmux…':error?'tmux 读取失败':snapshot?.reason||'选择会话窗格查看输出'}</p>{error&&<Notice tone="warning">{error}</Notice>}<select aria-label="tmux 窗格" value={pane} onChange={e=>setPane(e.target.value)}><option value="">选择 Pane</option>{snapshot?.sessions.flatMap(s=>s.windows.flatMap(w=>w.panes.map(p=><option key={p.id} value={p.id}>{s.name} / {w.index} / {p.id} · {p.command}</option>)))}</select><pre className="gpu-output">{snapshot?.content||'尚未取得输出。可进入交互终端执行 tmux ls 核对当前用户和会话。'}</pre></section>;
}
