import {useEffect,useRef,useState} from 'react';
import {useApp} from './store';
import {bridgeRequest} from './api';
import {Notice,Field,Modal} from './ui';
type Series={label:string;unit:string;current?:number|null;points:{time:number;value:number}[]};
export function GpuMetrics({taskId}:{taskId:string}){
  const [meta,setMeta]=useState<{maxDays?:string;startTime?:string;sampledAt?:string}>({});
  const {data,secrets}=useApp();const [series,setSeries]=useState<Series[]>([]),[message,setMessage]=useState('正在读取监测数据…');
  useEffect(()=>{let busy=false,alive=true;const c=new AbortController();
    const read=async()=>{if(busy||document.visibilityState!=='visible')return;busy=true;try{const r=await bridgeRequest(data.settings,secrets,'/gpu/task-monitor',{taskId},c.signal);if(alive){setSeries(r.series||[]);setMeta(r);setMessage(r.message||'');}}catch(e){if(alive)setMessage((e as Error).message);}finally{busy=false;}};
    setSeries([]);void read();const timer=setInterval(read,30000);return()=>{alive=false;c.abort();clearInterval(timer);};
  },[taskId,data.settings.bridgeUrl,secrets.bridgeKey]);
  return <section className="gpu-metrics"><h3>近 30 分钟资源消耗</h3><p className="muted">每 30 秒检查 · 按任务 ID 匹配 · 上报组内卡号不代表物理插槽</p><dl><dt>开始日期</dt><dd>{meta.startTime||"等待上报"}</dd><dt>Max days</dt><dd>{meta.maxDays||"等待上报"}</dd><dt>采样时间</dt><dd>{meta.sampledAt||"等待上报"}</dd></dl>{message&&<Notice tone="warning">{message}</Notice>}{series.map(s=>{
    const max=s.unit==='%'?100:Math.max(1,...s.points.map(p=>p.value))*1.1;const start=Date.now()-1800000;
    const paths:string[]=[];s.points.forEach((p,i)=>{const cmd=`${i===0||p.time-s.points[i-1].time>90000?'M':'L'}${Math.max(0,Math.min(400,(p.time-start)/1800000*400)).toFixed(1)},${(110-Math.min(1,p.value/max)*100).toFixed(1)}`;paths.push(cmd);});
    const last=s.points.at(-1),stale=last&&Date.now()-last.time>120000;
    return <div key={s.label} className="metric-chart"><strong>{s.label} {typeof s.current==='number'?`${s.current.toFixed(1)} ${s.unit}`:last?`${last.value.toFixed(1)} ${s.unit}`:'暂无数据'}</strong>{last&&<><small>{stale?'数据已滞后 · ':''}采样于 {new Date(last.time).toLocaleTimeString('zh-CN')}</small><svg role="img" aria-label={`${s.label}时间曲线，最大刻度 ${max.toFixed(0)} ${s.unit}`} viewBox="0 0 420 145"><text x="0" y="10">{max.toFixed(0)} {s.unit}</text><path d="M0,110 H400" stroke="currentColor" opacity=".2"/><path d={paths.join(' ')} fill="none" stroke="#318896" strokeWidth="2"/><text x="0" y="138">30 分钟前</text><text x="365" y="138">现在</text></svg></>}</div>;
  })}</section>;
}
type Task={id:string;description:string;state:string;pool:string;startTime:string;devices:{id:number;uuid:string}[]};
type Option={pool:string;file:string;available:number};
type Job={key:string;status:string;message:string;taskId:string};
export function GpuApply({pool,onCreated}:{pool:string;onCreated:()=>void}){
 const {data,secrets}=useApp();const [selectedPool,setSelectedPool]=useState(pool),[options,setOptions]=useState<Option[]>([]),[count,setCount]=useState('0'),[job,setJob]=useState<Job|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[fetched,setFetched]=useState(0);
 const key=useRef(crypto.randomUUID()),lock=useRef(false);
 const api=(p:string,b?:object)=>bridgeRequest(data.settings,secrets,p,b);
 useEffect(()=>{let alive=true;async function read(){try{const r=await api('/gpu/options');if(alive){setOptions(r.pools);setSelectedPool(current=>current||r.pools[0]?.pool||'');setFetched(Date.now());setError('');}}catch(e){if(alive){setFetched(0);setError((e as Error).message);}}}void read();const t=setInterval(()=>{if(document.visibilityState==='visible')void read();},30000);return()=>{alive=false;clearInterval(t);};},[data.settings.bridgeUrl,secrets.bridgeKey]);
 useEffect(()=>{if(job?.status!=='running')return;let alive=true;const t=setInterval(()=>{api('/gpu/job',{key:job.key}).then(j=>{if(alive){setJob(j);if(j.status!=='running')onCreated();}}).catch(e=>{if(alive)setError(e.message);});},2500);return()=>{alive=false;clearInterval(t);};},[job?.key,job?.status]);
 const option=options.find(o=>o.pool===selectedPool),n=count===''?NaN:Number(count),valid=!!option&&Number.isInteger(n)&&n>=0&&n<=option.available&&Date.now()-fetched<60000;
 async function apply(){if(lock.current||!valid)return;lock.current=true;setBusy(true);setError('');try{const j=await api('/gpu/submit',{pool:selectedPool,count:n,key:key.current});setJob(j);onCreated();}catch(e){setError((e as Error).message+'；如结果不确定，请先刷新我的任务核对。');}finally{lock.current=false;setBusy(false);}}
 return <section className="gpu-metrics"><h3>申请资源</h3><Field label="资源池"><select value={selectedPool} disabled={busy||!!job||!options.length} onChange={e=>setSelectedPool(e.target.value)}><option value="" disabled>请选择资源池</option>{selectedPool&&!options.some(o=>o.pool===selectedPool)&&<option value={selectedPool} disabled>{selectedPool}（不可用）</option>}{options.map(o=><option key={o.pool} value={o.pool}>{o.pool} · 可用 {o.available} 张</option>)}</select></Field><p>{selectedPool} · 当前可用 {option?.available??'—'} 张</p><p className="muted">模板：{option?.file||'等待连接后读取'}。由调度器选择实际板卡。</p><Field label="申请卡数（允许 0 卡）"><input type="number" min={0} max={option?.available??0} step={1} value={count} disabled={busy||!!job} onChange={e=>setCount(e.target.value)}/></Field><p className="muted">0 卡用于 CPU / 连接测试，能否调度取决于资源池策略。提交前本机再次校验可用量。</p><code>det shell start --config-file {option?.file||'…'} --config resources.slots={count||'…'} --config resources.resource_pool={selectedPool||'…'} --detach</code><p><button className="primary" disabled={!valid||busy||!!job} onClick={()=>void apply()}>{busy?'正在提交…':`直接申请 ${count||'…'} 张卡`}</button></p>{error&&<Notice tone="warning">{error}</Notice>}{job&&<Notice>{job.message}{job.taskId&&<p>任务 ID：<code>{job.taskId}</code></p>}</Notice>}</section>;
}
export function MyGpuTasks({revision}:{revision:number}){
 const {data,secrets}=useApp();const [tasks,setTasks]=useState<Task[]>([]),[selected,setSelected]=useState<Task|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const api=(p:string,b?:object)=>bridgeRequest(data.settings,secrets,p,b);
 async function refresh(){try{const r=await api('/gpu/tasks');setTasks(r.tasks);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(!secrets.bridgeKey)return;void refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},15000);return()=>clearInterval(t);},[revision,secrets.bridgeKey]);
 const current=tasks.find(t=>t.id===selected?.id)||selected;
 async function release(){if(!current||busy)return;if(!window.confirm(`释放任务 ${current.id}？这会终止该任务及其占用的全部显卡。`))return;setBusy(true);setMessage('');try{const r=await api('/gpu/kill',{taskId:current.id});setMessage(r.message);await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="surface local-gpu-apply"><div className="section-heading"><h2>集群任务</h2><button className="secondary" onClick={()=>void refresh()}>刷新任务</button></div><p className="muted">显示集群授权可见的任务，包括 0 卡任务；每 15 秒同步。关闭网页不会释放资源。</p>{error&&<Notice tone="warning">{error}</Notice>}{!tasks.length&&<p>暂无可显示的任务；请先连接 / 登录后刷新。</p>}{tasks.map(t=><button className="secondary" style={{display:'block',width:'100%',textAlign:'left',marginBottom:8}} key={t.id} onClick={()=>{setSelected(t);setMessage('');}}><strong>{t.description||t.id}</strong><p>{t.pool} · {t.state} · 已分配 {t.devices.length} 张</p><small>{t.id} · 开始于 {new Date(t.startTime).toLocaleString('zh-CN')}</small></button>)}{current&&<Modal drawer title="我的任务 · 监控与释放" onClose={()=>setSelected(null)}><div className="gpu-detail"><h3>{current.description}</h3><p>任务 ID：<code>{current.id}</code></p><p>{current.pool} · {current.state}</p><p>集群开始时间：{new Date(current.startTime).toLocaleString('zh-CN')}</p><GpuMetrics key={current.id} taskId={current.id}/><p>本机连接命令：</p><pre>det shell open {current.id}</pre><button className="secondary" onClick={()=>void navigator.clipboard.writeText(`det shell open ${current.id}`).then(()=>setMessage('连接命令已复制'),()=>setMessage('复制失败，请手动复制上方命令'))}>复制连接命令</button><p><button className="primary" disabled={busy||!!error||/TERMINATED|COMPLETED/.test(current.state)} onClick={()=>void release()}>{busy?'正在释放…':'释放此任务全部资源'}</button></p>{message&&<Notice>{message}</Notice>}</div></Modal>}</section>;
}
